### ISSUE TITLE
Cheers for making this

### ISSUE THREAD

**Issue by Frankloco** [Filodoxia/eft-hideout-upgrades#2]
Hi, I would like to thank you for creating this interactive version of the Hideout Flowchart. It's brilliant. I made the original image version on the wiki. This expanded version is so much cooler. It's awesome to see you kept the same style, with lots of improvements. Not sure how I else could make a remark on this. Hence me making an 'issue'. But thank you!

**Comment by Filodoxia** [comment]
Thank you for making the original version. It inspired me to even start this in the first place. I'm glad it is helpful and will try to update it from time to time, even if I don't have much time atm and therefore have not been playing much EFT lately.
